version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: dtslint
    versions:
    - "> 3.3.0"
  - dependency-name: mocha
    versions:
    - "> 7.2.0"
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: sinon
    versions:
    - 10.0.0
